-- Installation instructions:
-- 1. Save this file as mycustomproto.lua
-- 2. In Wireshark, go to Help -> About Wireshark -> Folders
-- 3. Open the "Personal Lua Plugins" folder
-- 4. Copy this file into that folder
-- 5. Restart Wireshark or press Ctrl+Shift+L to reload Lua plugins
--
-- Usage:
-- - Set the protocol port in Edit -> Preferences -> Protocols -> MyCustomProto
-- - Or use heuristic dissection if magic bytes are detected
--
-- Generated fields:

--   [0x0000] fixed_0000 (3 bytes) - ENUM

--   [0x0003] variable_0003 (2 bytes) - INTEGER

--   [0x0005] fixed_0005 (1 bytes) - INTEGER

--   [0x0006] variable_0006 (2 bytes) - INTEGER

--   [0x0008] fixed_0008 (2 bytes) - INTEGER

--   [0x000A] variable_000a (1 bytes) - INTEGER

--   [0x000B] fixed_000b (1 bytes) - INTEGER

--   [0x000C] variable_000c (11 bytes) - INTEGER

--   [0x0017] fixed_0017 (285 bytes) - UNKNOWN

--   [0x0134] unknown_data (-1 bytes) - BYTES

-- Wireshark dissector for MyCustomProto
-- Generated by Protocol Reverse Engineering Toolkit
-- 2026-05-23T19:05:38.245774

local mycustomproto_proto = Proto("mycustomproto", "Reverse engineered protocol from 15 messages")

-- Protocol fields
local fields = {

    
    fixed_0000 = ProtoField.bytes("mycustomproto.fixed_0000", "fixed_0000 (Fixed)", base.HEX),
    

    
    variable_0003 = ProtoField.uint16("mycustomproto.variable_0003", "variable_0003", base.DEC),
    

    
    fixed_0005 = ProtoField.uint8("mycustomproto.fixed_0005", "fixed_0005 (Fixed)", base.HEX),
    

    
    variable_0006 = ProtoField.uint16("mycustomproto.variable_0006", "variable_0006", base.DEC),
    

    
    fixed_0008 = ProtoField.uint16("mycustomproto.fixed_0008", "fixed_0008 (Fixed)", base.HEX),
    

    
    variable_000a = ProtoField.uint8("mycustomproto.variable_000a", "variable_000a", base.DEC),
    

    
    fixed_000b = ProtoField.uint8("mycustomproto.fixed_000b", "fixed_000b (Fixed)", base.HEX),
    

    
    variable_000c = ProtoField.bytes("mycustomproto.variable_000c", "variable_000c", base.DEC),
    

    
    fixed_0017 = ProtoField.bytes("mycustomproto.fixed_0017", "fixed_0017 (Fixed)", base.HEX),
    

    
    unknown_data = ProtoField.bytes("mycustomproto.unknown_data", "unknown_data", base.SPACE),
    

}

mycustomproto_proto.fields = {

    fields.fixed_0000,

    fields.variable_0003,

    fields.fixed_0005,

    fields.variable_0006,

    fields.fixed_0008,

    fields.variable_000a,

    fields.fixed_000b,

    fields.variable_000c,

    fields.fixed_0017,

    fields.unknown_data,

}

-- Expert info
local expert = {
    malformed = ProtoExpert.new("mycustomproto.malformed", "Malformed packet", expert.group.MALFORMED, expert.severity.ERROR),

}

mycustomproto_proto.experts = {
    expert.malformed,

}

-- Dissector function
function mycustomproto_proto.dissector(buffer, pinfo, tree)
    local buf_len = buffer:len()

    if buf_len < 3 then
        local subtree = tree:add(mycustomproto_proto, buffer())
        subtree:add_proto_expert_info(expert.malformed)
        return
    end

    pinfo.cols.protocol = "MYCUSTOMPROTO"
    pinfo.cols.info = "MyCustomProto packet"

    local subtree = tree:add(mycustomproto_proto, buffer(), "MyCustomProto Protocol Data")

    -- Parsed fields

    
    if 0 + 3 <= buf_len then
        do
            local field_buffer = buffer(0, 3)
            local field_name = fields.fixed_0000.name

            
            subtree:add_packet_field(fields.fixed_0000, field_buffer, ENC_LITTLE_ENDIAN)
            

            

            

            
        end
    end
    

    
    if 3 + 2 <= buf_len then
        do
            local field_buffer = buffer(3, 2)
            local field_name = fields.variable_0003.name

            
            subtree:add_packet_field(fields.variable_0003, field_buffer, ENC_LITTLE_ENDIAN)
            

            

            

            
            -- Note: Low confidence field (0.26666666666666666)
            
        end
    end
    

    
    if 5 + 1 <= buf_len then
        do
            local field_buffer = buffer(5, 1)
            local field_name = fields.fixed_0005.name

            
            subtree:add_packet_field(fields.fixed_0005, field_buffer, ENC_LITTLE_ENDIAN)
            

            

            

            
        end
    end
    

    
    if 6 + 2 <= buf_len then
        do
            local field_buffer = buffer(6, 2)
            local field_name = fields.variable_0006.name

            
            subtree:add_packet_field(fields.variable_0006, field_buffer, ENC_LITTLE_ENDIAN)
            

            

            

            
            -- Note: Low confidence field (0.1)
            
        end
    end
    

    
    if 8 + 2 <= buf_len then
        do
            local field_buffer = buffer(8, 2)
            local field_name = fields.fixed_0008.name

            
            subtree:add_packet_field(fields.fixed_0008, field_buffer, ENC_LITTLE_ENDIAN)
            

            

            

            
        end
    end
    

    
    if 10 + 1 <= buf_len then
        do
            local field_buffer = buffer(10, 1)
            local field_name = fields.variable_000a.name

            
            subtree:add_packet_field(fields.variable_000a, field_buffer, ENC_LITTLE_ENDIAN)
            

            

            
            local length_val = field_buffer:le_uint()
            pinfo.cols.info:append(" Len=" .. length_val)
            

            
        end
    end
    

    
    if 11 + 1 <= buf_len then
        do
            local field_buffer = buffer(11, 1)
            local field_name = fields.fixed_000b.name

            
            subtree:add_packet_field(fields.fixed_000b, field_buffer, ENC_LITTLE_ENDIAN)
            

            

            

            
        end
    end
    

    
    if 12 + 11 <= buf_len then
        do
            local field_buffer = buffer(12, 11)
            local field_name = fields.variable_000c.name

            
            subtree:add_packet_field(fields.variable_000c, field_buffer, ENC_LITTLE_ENDIAN)
            

            

            

            
            -- Note: Low confidence field (0.0974025974025974)
            
        end
    end
    

    
    if 23 + 285 <= buf_len then
        do
            local field_buffer = buffer(23, 285)
            local field_name = fields.fixed_0017.name

            
            subtree:add_packet_field(fields.fixed_0017, field_buffer, ENC_NA)
            

            

            

            
        end
    end
    

    


    -- Remaining data
    local parsed_offset = 308
    if parsed_offset < buf_len then
        local remaining = buffer(parsed_offset)
        subtree:add(mycustomproto_proto.fields.unknown_data, remaining, "Remaining data")
    end
end

-- Register dissector
local tcp_table = DissectorTable.get("tcp.port")
local udp_table = DissectorTable.get("udp.port")

-- Default ports (can be changed in Wireshark preferences)
mycustomproto_proto.prefs.tcp_port = Pref.uint("TCP Port", 0, "TCP port for MyCustomProto")
mycustomproto_proto.prefs.udp_port = Pref.uint("UDP Port", 0, "UDP port for MyCustomProto")

function mycustomproto_proto.prefs_changed()
    -- Remove old registrations
    if mycustomproto_proto.prefs.tcp_port > 0 then
        tcp_table:add(mycustomproto_proto.prefs.tcp_port, mycustomproto_proto)
    end
    if mycustomproto_proto.prefs.udp_port > 0 then
        udp_table:add(mycustomproto_proto.prefs.udp_port, mycustomproto_proto)
    end
end

-- Heuristic dissector
local function heur_dissect(buffer, pinfo, tree)
    if buffer:len() < 3 then
        return false
    end

    -- Check for magic bytes or known patterns

    local magic = buffer(0, 3):uint()
    if magic ~= 0x341201 then
        return false
    end


    -- Additional heuristics: check for reasonable field values

    local len_field = buffer(10, 1):le_uint()
    if len_field > buffer:len() * 2 or len_field == 0 then
        return false
    end


    mycustomproto_proto.dissector(buffer, pinfo, tree)
    return true
end

mycustomproto_proto:register_heuristic("tcp", heur_dissect)
mycustomproto_proto:register_heuristic("udp", heur_dissect)

print("MyCustomProto dissector loaded")