"""Wireshark Lua dissector generator."""

from dataclasses import dataclass, field
from typing import List, Dict, Optional, Tuple
import os


LUA_DISSECTOR_TEMPLATE = """-- Wireshark dissector for {{ protocol_name }}
-- Generated by Protocol Reverse Engineering Toolkit
-- {{ generated_at }}

local {{ proto_var }} = Proto("{{ proto_name }}", "{{ protocol_description }}")

-- Protocol fields
local fields = {
{% for field in fields %}
    {% if field.field_type == 'fixed' %}
    {{ field.name }} = ProtoField.{{ get_uint_type(field.length) }}("{{ proto_name }}.{{ field.name }}", "{{ field.name }} (Fixed)", base.HEX),
    {% elif field.inferred_type == 'integer' %}
    {{ field.name }} = ProtoField.{{ get_uint_type(field.length) }}("{{ proto_name }}.{{ field.name }}", "{{ field.name }}", base.DEC),
    {% elif field.inferred_type == 'float' %}
    {{ field.name }} = ProtoField.float("{{ proto_name }}.{{ field.name }}", "{{ field.name }}"),
    {% elif field.inferred_type == 'timestamp' %}
    {{ field.name }} = ProtoField.absolute_time("{{ proto_name }}.{{ field.name }}", "{{ field.name }}"),
    {% elif field.inferred_type == 'enum' %}
    {{ field.name }} = ProtoField.uint8("{{ proto_name }}.{{ field.name }}", "{{ field.name }}", base.DEC, {{ generate_enum_table(field.enum_values) }}),
    {% elif field.inferred_type == 'ascii' %}
    {{ field.name }} = ProtoField.string("{{ proto_name }}.{{ field.name }}", "{{ field.name }}"),
    {% elif field.is_checksum %}
    {{ field.name }} = ProtoField.{{ get_uint_type(field.length) }}("{{ proto_name }}.{{ field.name }}", "{{ field.name }} ({{ field.checksum_type }})", base.HEX),
    {% elif field.is_length_field %}
    {{ field.name }} = ProtoField.{{ get_uint_type(field.length) }}("{{ proto_name }}.{{ field.name }}", "{{ field.name }} (Length)", base.DEC),
    {% else %}
    {{ field.name }} = ProtoField.bytes("{{ proto_name }}.{{ field.name }}", "{{ field.name }}", base.SPACE),
    {% endif %}
{% endfor %}
}

{{ proto_var }}.fields = {
{% for field in fields %}
    fields.{{ field.name }},
{% endfor %}
}

-- Expert info
local expert = {
    malformed = ProtoExpert.new("{{ proto_name }}.malformed", "Malformed packet", expert.group.MALFORMED, expert.severity.ERROR),
{% if has_checksum %}
    bad_checksum = ProtoExpert.new("{{ proto_name }}.bad_checksum", "Bad checksum", expert.group.CHECKSUM, expert.severity.WARN),
{% endif %}
}

{{ proto_var }}.experts = {
    expert.malformed,
{% if has_checksum %}
    expert.bad_checksum,
{% endif %}
}

-- Dissector function
function {{ proto_var }}.dissector(buffer, pinfo, tree)
    local buf_len = buffer:len()

    if buf_len < {{ min_length }} then
        local subtree = tree:add({{ proto_var }}, buffer())
        subtree:add_proto_expert_info(expert.malformed)
        return
    end

    pinfo.cols.protocol = "{{ proto_name_upper }}"
    pinfo.cols.info = "{{ protocol_name }} packet"

    local subtree = tree:add({{ proto_var }}, buffer(), "{{ protocol_name }} Protocol Data")

    -- Parsed fields
{% for field in fields %}
    {% if field.length > 0 %}
    if {{ field.offset }} + {{ field.length }} <= buf_len then
        do
            local field_buffer = buffer({{ field.offset }}, {{ field.length }})
            local field_name = fields.{{ field.name }}.name

            {% if field.inferred_type == 'timestamp' %}
            local ts_val = field_buffer:le_uint()
            if ts_val > 0 then
                subtree:add_packet_field(fields.{{ field.name }}, field_buffer, ENC_LITTLE_ENDIAN)
            end
            {% elif field.inferred_type == 'ascii' %}
            subtree:add_packet_field(fields.{{ field.name }}, field_buffer, ENC_ASCII)
            {% elif field.inferred_type == 'float' %}
            subtree:add_packet_field(fields.{{ field.name }}, field_buffer, ENC_LITTLE_ENDIAN)
            {% elif field.is_checksum or field.is_length_field or field.inferred_type == 'integer' or field.inferred_type == 'enum' %}
            subtree:add_packet_field(fields.{{ field.name }}, field_buffer, ENC_LITTLE_ENDIAN)
            {% else %}
            subtree:add_packet_field(fields.{{ field.name }}, field_buffer, ENC_NA)
            {% endif %}

            {% if field.is_checksum %}
            -- Checksum verification (placeholder)
            -- subtree:add_tvb_expert_info(expert.bad_checksum, field_buffer)
            {% endif %}

            {% if field.is_length_field %}
            local length_val = field_buffer:le_uint()
            pinfo.cols.info:append(" Len=" .. length_val)
            {% endif %}

            {% if field.confidence < 0.7 %}
            -- Note: Low confidence field ({{ field.confidence }})
            {% endif %}
        end
    end
    {% endif %}
{% endfor %}

    -- Remaining data
    local parsed_offset = {{ max_offset }}
    if parsed_offset < buf_len then
        local remaining = buffer(parsed_offset)
        subtree:add({{ proto_var }}.fields.unknown_data, remaining, "Remaining data")
    end
end

-- Register dissector
local tcp_table = DissectorTable.get("tcp.port")
local udp_table = DissectorTable.get("udp.port")

-- Default ports (can be changed in Wireshark preferences)
{{ proto_var }}.prefs.tcp_port = Pref.uint("TCP Port", 0, "TCP port for {{ protocol_name }}")
{{ proto_var }}.prefs.udp_port = Pref.uint("UDP Port", 0, "UDP port for {{ protocol_name }}")

function {{ proto_var }}.prefs_changed()
    -- Remove old registrations
    if {{ proto_var }}.prefs.tcp_port > 0 then
        tcp_table:add({{ proto_var }}.prefs.tcp_port, {{ proto_var }})
    end
    if {{ proto_var }}.prefs.udp_port > 0 then
        udp_table:add({{ proto_var }}.prefs.udp_port, {{ proto_var }})
    end
end

-- Heuristic dissector
local function heur_dissect(buffer, pinfo, tree)
    if buffer:len() < {{ min_length }} then
        return false
    end

    -- Check for magic bytes or known patterns
{% if magic_bytes %}
    local magic = buffer(0, {{ magic_length }}):uint()
    if magic ~= 0x{{ magic_bytes }} then
        return false
    end
{% endif %}

    -- Additional heuristics: check for reasonable field values
{% for check in heuristic_checks %}
    {{ check }}
{% endfor %}

    {{ proto_var }}.dissector(buffer, pinfo, tree)
    return true
end

{{ proto_var }}:register_heuristic("tcp", heur_dissect)
{{ proto_var }}:register_heuristic("udp", heur_dissect)

print("{{ protocol_name }} dissector loaded")
"""

DISSECTOR_HEADER_COMMENTS = """-- Installation instructions:
-- 1. Save this file as {{ proto_name }}.lua
-- 2. In Wireshark, go to Help -> About Wireshark -> Folders
-- 3. Open the "Personal Lua Plugins" folder
-- 4. Copy this file into that folder
-- 5. Restart Wireshark or press Ctrl+Shift+L to reload Lua plugins
--
-- Usage:
-- - Set the protocol port in Edit -> Preferences -> Protocols -> {{ protocol_name }}
-- - Or use heuristic dissection if magic bytes are detected
--
-- Generated fields:
{% for field in fields %}
--   [0x{{ '%04X'|format(field.offset) }}] {{ field.name }} ({{ field.length }} bytes) - {{ field.inferred_type|upper }}
{% endfor %}
"""


@dataclass
class LuaDissectorGenerator:
    """Generates Wireshark Lua dissector from protocol description."""

    def __init__(self, protocol_name: str = "UnknownProtocol"):
        self.protocol_name = protocol_name

    def _get_uint_type(self, length: int) -> str:
        """Get appropriate uint type for a given length."""
        if length == 1:
            return 'uint8'
        elif length == 2:
            return 'uint16'
        elif length == 4:
            return 'uint32'
        elif length == 8:
            return 'uint64'
        else:
            return 'bytes'

    def _generate_enum_table(self, enum_values: Dict) -> str:
        """Generate Lua table for enum values."""
        if not enum_values:
            return 'nil'

        entries = []
        for val, count in sorted(enum_values.items(), key=lambda x: int(x[0])):
            entries.append(f'[{val}] = "Value {val}"')

        return '{' + ', '.join(entries) + '}'

    def _extract_magic_bytes(self, fields: List[Dict]) -> Tuple[Optional[str], int]:
        """Extract magic bytes from fixed header fields."""
        for field in fields:
            if field.get('offset', 0) == 0 and field.get('is_fixed', True):
                samples = field.get('sample_values', [])
                if samples:
                    try:
                        magic_str = samples[0]
                        if isinstance(magic_str, str):
                            magic_bytes = bytes.fromhex(magic_str.replace(' ', ''))
                        else:
                            magic_bytes = magic_str
                        if len(magic_bytes) >= 2:
                            return magic_bytes[:4].hex(), min(len(magic_bytes), 4)
                    except (IndexError, TypeError, ValueError):
                        pass
        return None, 0

    def _generate_heuristic_checks(self, fields: List[Dict]) -> List[str]:
        """Generate heuristic validation checks."""
        checks = []

        for field in fields:
            if field.get('is_length_field'):
                offset = field['offset']
                length = field['length']
                checks.append(
                    f'local len_field = buffer({offset}, {length}):le_uint()\n'
                    f'    if len_field > buffer:len() * 2 or len_field == 0 then\n'
                    f'        return false\n'
                    f'    end'
                )

            if field.get('inferred_type') == 'timestamp' and field.get('offset', 0) < 100:
                offset = field['offset']
                length = field['length']
                checks.append(
                    f'local ts_field = buffer({offset}, {length}):le_uint()\n'
                    f'    if ts_field < 946684800 or ts_field > 2524608000 then\n'
                    f'        return false\n'
                    f'    end'
                )

        return checks

    def generate(self, protocol_desc: Dict, output_path: Optional[str] = None) -> str:
        """Generate Lua dissector code."""
        try:
            from jinja2 import Template
        except ImportError as e:
            raise ImportError("jinja2 is required. Install with: pip install jinja2") from e

        fields = protocol_desc.get('fields', [])
        magic_bytes, magic_length = self._extract_magic_bytes(fields)
        heuristic_checks = self._generate_heuristic_checks(fields)

        has_checksum = any(f.get('is_checksum', False) for f in fields)
        has_unknown = any(f.get('inferred_type') == 'unknown' for f in fields)

        min_length = min(f['offset'] + f['length'] for f in fields) if fields else 1
        max_offset = max(f['offset'] + f['length'] for f in fields) if fields else 0

        if has_unknown:
            fields = fields.copy()
            fields.append({
                'name': 'unknown_data',
                'offset': max_offset,
                'length': -1,
                'field_type': 'variable',
                'inferred_type': 'bytes',
                'confidence': 0.5
            })

        template = Template(LUA_DISSECTOR_TEMPLATE)
        header_template = Template(DISSECTOR_HEADER_COMMENTS)

        import datetime
        generated_at = datetime.datetime.now().isoformat()

        proto_name = self.protocol_name.lower().replace(' ', '_')
        proto_var = proto_name + '_proto'
        proto_name_upper = proto_name.upper()

        context = {
            'protocol_name': self.protocol_name,
            'protocol_description': protocol_desc.get('description', f'{self.protocol_name} Protocol'),
            'proto_name': proto_name,
            'proto_var': proto_var,
            'proto_name_upper': proto_name_upper,
            'generated_at': generated_at,
            'fields': fields,
            'magic_bytes': magic_bytes,
            'magic_length': magic_length,
            'heuristic_checks': heuristic_checks,
            'has_checksum': has_checksum,
            'min_length': min_length,
            'max_offset': max_offset,
            'get_uint_type': self._get_uint_type,
            'generate_enum_table': self._generate_enum_table,
        }

        header = header_template.render(context)
        body = template.render(context)

        lua_code = header + '\n' + body

        if output_path:
            output_dir = os.path.dirname(output_path)
            if output_dir and not os.path.exists(output_dir):
                os.makedirs(output_dir, exist_ok=True)

            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(lua_code)
            print(f"[+] Wireshark dissector saved to {output_path}")

        return lua_code

    def generate_quick_start(self, protocol_name: str, output_dir: str) -> Dict[str, str]:
        """Generate a quick start package with installation instructions."""
        lua_path = os.path.join(output_dir, f'{protocol_name.lower()}_dissector.lua')
        lua_code = self.generate({'fields': []}, lua_path)

        readme_content = f"""# {protocol_name} Wireshark Dissector

## Installation

1. Copy `{protocol_name.lower()}_dissector.lua` to your Wireshark plugins folder:
   - Windows: `%APPDATA%\\Wireshark\\plugins\\`
   - macOS: `~/.config/wireshark/plugins/`
   - Linux: `~/.config/wireshark/plugins/`

2. Restart Wireshark or press `Ctrl+Shift+L` to reload Lua plugins

3. Configure port in Wireshark:
   - Edit -> Preferences -> Protocols -> {protocol_name}
   - Set TCP/UDP port numbers

## Usage

```bash
# Filter for protocol in Wireshark
{protocol_name.lower()}

# Filter by specific field
{protocol_name.lower()}.field_name == value
```

## Generated Fields

The dissector automatically parses the following fields based on the reverse-engineered protocol:
- Fixed header fields
- Variable data fields
- Length fields
- Checksum fields
- Type/enum fields

## Troubleshooting

- If dissection doesn't work, check that the port is correctly configured
- Enable heuristic dissection in Wireshark preferences
- Check the Wireshark console for Lua errors
"""

        readme_path = os.path.join(output_dir, 'README.md')
        with open(readme_path, 'w', encoding='utf-8') as f:
            f.write(readme_content)

        return {
            'lua': lua_path,
            'readme': readme_path
        }
